#!/bin/bash

# create proper environment
idir=/home/chess_chapaas/chess/CHAPaaS
if [ "`whoami`" == "chessdata_svc"  ]; then
    idir=/home/chessdata_svc/CHAPBook/src/CHAPaaS
elif [ "`whoami`" == "chess_chapaas"  ]; then
    idir=/home/chess_chapaas/chess/CHAPaaS
else
    echo "Unsupported account: `whoami`"
    exit 1
fi
jdir=$idir/jupyter
cdir=$idir/chap
unset PYTHONPATH
source venv/bin/activate
mkdir -p $jdir/logs
mkdir -p $cdir/logs

#
# local functions
# 

start_jupyter() {
    # start jupyter server
    mkdir -p $jdir/logs
    cd $jdir
    echo "starting Jupyter notebook server in $PWD"
    nohup jupyter notebook --config $idir/scripts/jupyter_config.py \
        2>&1 1>& $jdir/logs/jupyter.log < /dev/null & \
        echo $! > $jdir/logs/jupyter.pid
    echo "Jupyter notebook PID=`cat $jdir/logs/jupyter.pid`"
    echo "Jupyter notebook logs $jdir/logs/jupyter.log"
    cd -
}

start_chapaas() {
    # start chapaas server
    cd $cdir
    echo "starting chapaas server in $PWD"
    nohup $idir/chapaas -config $idir/config-http.json \
        2>&1 1>& $cdir/logs/chapaas.log < /dev/null & \
        echo $! > $cdir/logs/chapaas.pid
    echo "chapaas PID=`cat $cdir/logs/chapaas.pid`"
    echo "chapaas logs $cdir/logs/chapaas.log"
    cd $idir
}

status() {
    echo "Current chap processes:"
    ps axu | grep --color=auto -v grep | grep --color=auto "chap" -i --color=auto
    sleep 3
    echo
    echo "Jupyter tail $jdir/logs/jupyter.log"
    tail $jdir/logs/jupyter.log
    echo
    echo "CHAPaaS tail $cdir/logs/chapaas.log"
    tail $cdir/logs/chapaas.log
}

start() {
    start_jupyter;
    start_chapaas;
    status;
}

stop_jupyter() {
#     local pid=`ps auxwww | egrep "chapaas.*jupyter" | grep -v grep | awk 'BEGIN{ORS=" "} {print $2}'`
#     echo "Stop chapaas jupyter  service... ${pid}"
#     if [ -n "${pid}" ]; then
#         echo "${pid}" | sed "s, $,,g" | sed "s, ,\n,g" | awk '{print "kill -9 "$1""}'
#     fi
    jpid=`ps auxww | grep "chapaas.*jupyter-notebook --config" | grep -v grep | awk '{print $2}'`
    if [ -n "$jpid" ]; then
        echo "kill previous jupyter-notebook process $jpid"
        kill -9 $jpid
    fi
}
stop_chapaas() {
#     local pid=`ps auxwww | egrep "chapaas.* -config" | grep -v grep | awk 'BEGIN{ORS=" "} {print $2}'`
#     echo "Stop chapaas service... ${pid}"
#     if [ -n "${pid}" ]; then
#         echo "${pid}" | sed "s, $,,g" | sed "s, ,\n,g" | awk '{print "kill -9 "$1""}'
#     fi
    cpid=`ps auxww | grep "chapaas -config" | grep -v grep | awk '{print $2}'`
    if [ -n "$cpid" ]; then
        echo "kill previous chapaas process $cpid"
        kill -9 $cpid
    fi
}
stop() {
    stop_jupyter;
    stop_chapaas;
}

help() {
   echo "Usage: manage <start|stop|status>"
}

#
# Main
#

case $1 in
  status)
    status
    ;;
  stop)
    stop
    ;;
  start)
    start
    ;;
  restart)
    stop
    start
    ;;
  help)
    help
    ;;
  * )
    echo "$0: unknown action '$1', please try '$0 help' or documentation." 1>&2
    exit 1 ;;
esac
