#!/bin/bash

COLOR_OK="\\033[0;32m"
COLOR_WARN="\\033[0;31m"
COLOR_NORMAL="\\033[0;39m"
echo_e=-e
case $(uname) in Darwin )
  md5sum() { md5 -r ${1+"$@"}; }
  echo_e=
  ;;
esac

# create proper environment
idir=/home/chess_chapaas/chess/CHAPaaS
if [ "`whoami`" == "chessdata_svc"  ]; then
    idir=/home/chessdata_svc/CHAPBook/src/CHAPaaS
    # setup conda env
    if [ -f /home/chessdata_svc/miniconda3/etc/profile.d/conda.sh ]; then
        source /home/chessdata_svc/miniconda3/etc/profile.d/conda.sh
    fi
elif [ "`whoami`" == "chess_chapaas"  ]; then
    idir=/home/chess_chapaas/chess/CHAPaaS
else
    echo "Unsupported account: `whoami`"
    exit 1
fi
jdir=$idir/jupyter
cdir=$idir/chap
unset PYTHONPATH
source venv/bin/activate
mkdir -p $jdir/logs
mkdir -p $cdir/logs

#
# local functions
# 
status_srv() {
    echo $echo_e "${COLOR_WARN}Checking chap services...${COLOR_NORMAL}"
    sleep 3

    # check chapaas jupyter service
    jpid=`ps auxww | grep "chapaas.*jupyter-notebook --config" | grep -v grep | awk '{print $2}'`
    if [ -n "$jpid" ]; then
        echo
        echo $echo_e "chapaas jupyter service is ${COLOR_OK}RUNNING${COLOR_NORMAL}, PID=${jpid}"
        echo $echo_e "${COLOR_OK}Jupyter$ $jdir/logs/jupyter.log${COLOR_NORMAL}"
        tail -5 $jdir/logs/jupyter.log
    else
        echo $echo_e "chapaas jupyter service is ${COLOR_WARN}NOT RUNNING${COLOR_NORMAL}"
    fi

    # check chapaas service
    cpid=`ps auxww | grep "chapaas -config" | grep -v grep | awk '{print $2}'`
    if [ -n "$cpid" ]; then
        echo
        echo $echo_e "chapaas service is ${COLOR_OK}RUNNING${COLOR_NORMAL}, PID=${cpid}"
        echo $echo_e "${COLOR_OK}CHAPaaS $cdir/logs/chapaas.log${COLOR_NORMAL}"
        tail -5 $cdir/logs/chapaas.log
    else
        echo $echo_e "chapaas service is ${COLOR_WARN}NOT RUNNING${COLOR_NORMAL}"
    fi
}


start_jupyter() {
    # start jupyter server
    mkdir -p $jdir/logs
    cd $jdir
    echo "starting Jupyter notebook server in $PWD"
    nohup jupyter notebook --config $idir/scripts/jupyter_config.py \
        2>&1 1>& $jdir/logs/jupyter.log < /dev/null & \
        echo $! > $jdir/logs/jupyter.pid
    echo "Jupyter notebook PID=`cat $jdir/logs/jupyter.pid`"
    echo "Jupyter notebook logs $jdir/logs/jupyter.log"
    cd -
}

start_chapaas() {
    # start chapaas server
    cd $cdir
    echo "starting chapaas server in $PWD"
    nohup $idir/chapaas -config $idir/config.json \
        2>&1 1>& $cdir/logs/chapaas.log < /dev/null & \
        echo $! > $cdir/logs/chapaas.pid
    echo "chapaas PID=`cat $cdir/logs/chapaas.pid`"
    echo "chapaas logs $cdir/logs/chapaas.log"
    cd $idir
}

start_srv() {
    start_jupyter;
    start_chapaas;
    status_srv;
}

stop_jupyter() {
#     local pid=`ps auxwww | egrep "chapaas.*jupyter" | grep -v grep | awk 'BEGIN{ORS=" "} {print $2}'`
#     echo "Stop chapaas jupyter  service... ${pid}"
#     if [ -n "${pid}" ]; then
#         echo "${pid}" | sed "s, $,,g" | sed "s, ,\n,g" | awk '{print "kill -9 "$1""}'
#     fi
    jpid=`ps auxww | grep "chapaas.*jupyter-notebook --config" | grep -v grep | awk '{print $2}'`
    if [ -n "$jpid" ]; then
        echo "kill previous jupyter-notebook process $jpid"
        kill -9 $jpid
    fi
}
stop_chapaas() {
#     local pid=`ps auxwww | egrep "chapaas.* -config" | grep -v grep | awk 'BEGIN{ORS=" "} {print $2}'`
#     echo "Stop chapaas service... ${pid}"
#     if [ -n "${pid}" ]; then
#         echo "${pid}" | sed "s, $,,g" | sed "s, ,\n,g" | awk '{print "kill -9 "$1""}'
#     fi
    cpid=`ps auxww | grep "chapaas -config" | grep -v grep | awk '{print $2}'`
    if [ -n "$cpid" ]; then
        echo "kill previous chapaas process $cpid"
        kill -9 $cpid
    fi
}

stop_srv() {
    stop_jupyter;
    stop_chapaas;
}

help_srv() {
   echo "Usage: manage <start|stop|status>"
}

#
# Main
#

case $1 in
  status)
    status_srv
    ;;
  stop)
    stop_srv
    ;;
  start)
    start_srv
    ;;
  restart)
    stop_srv
    start_srv
    ;;
  help)
    help_srv
    ;;
  * )
    echo "$0: unknown action '$1', please try '$0 help'" 1>&2
    exit 1 ;;
esac
